In [12]:
import numpy as np
a1=np.arange(4).reshape(2,2)
print(a1)
a2=np.arange(4,8).reshape(2,2)
print(a2)
arr=np.add(a1,a2)
print(arr)
print("subtraction:")
print(np.subtract(a1,a2))
print("multiplication")
print(np.multiply(a1,a2))
print("division:")
print(np.divide(a1,4))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 4  6]
 [ 8 10]]
subtraction:
[[-4 -4]
 [-4 -4]]
multiplication
[[ 0  5]
 [12 21]]
division:
[[0.   0.25]
 [0.5  0.75]]


In [3]:
import numpy as np
a=np.arange(8).reshape(4,2)
b=np.divide(a,2)
print(b)


[[0.  0.5]
 [1.  1.5]
 [2.  2.5]
 [3.  3.5]]


In [5]:
import numpy as np
a=np.arange(6)
b=np.power(a,2)
print(b)

[ 0  1  4  9 16 25]


In [9]:
import numpy as np
a=np.arange(-20,-10)
print(a)
b=np.abs(a)
print(b)

[-20 -19 -18 -17 -16 -15 -14 -13 -12 -11]
[20 19 18 17 16 15 14 13 12 11]


In [26]:
import numpy as np
a=np.random.rand(4)
print (a)
np.round(a,decimals=1)

[0.32013776 0.18074856 0.70924794 0.16083133]


array([0.3, 0.2, 0.7, 0.2])

In [34]:
import numpy as np
a=np.linspace(2.0,3.0,5)
print(a)
floor=np.floor(a)
print(floor)
c=np.ceil(a)
print(c)
t=np.trunc(a)
print(t)

[2.   2.25 2.5  2.75 3.  ]
[2. 2. 2. 2. 3.]
[2. 3. 3. 3. 3.]
[2. 2. 2. 2. 3.]


In [37]:
import numpy as np
a=np.arange(15).reshape(5,3)
print(a)
b=np.arange(6).reshape(3,2)
print(b)
c=np.dot(a,b)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [42]:
import numpy as np
arr=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi])
arr=np.degrees(arr)
print(arr)
a=np.sin(arr)
print(a)

[ 90.  60.  45. 180.]
[ 0.89399666 -0.30481062  0.85090352 -0.80115264]


In [45]:
import numpy as np
a=np.arange(5)
np.median(a)

2.0

In [49]:
import numpy as np
a=np.arange(0,101,20)
print("mean of array")
print(np.mean(a))
print("standard deviation")
print(np.round(np.std(a),2))

mean of array
50.0
standard deviation
34.16
